/* eslint-disable import/prefer-default-export */
export const RETRIEVE_PROFILE_SUCCESS = 'RETRIEVE_PROFILE_SUCCESS';
export const RETRIEVE_PROFILE_ERROR = 'RETRIEVE_PROFILE_ERROR';
export const RETRIEVE_VISITED_PROFILE_SUCCESS = 'RETRIEVE_VISITED_PROFILE_SUCCESS';
export const RETRIEVE_VISITED_PROFILE_ERROR = 'RETRIEVE_VISITED_PROFILE_ERROR';
